export const destinos = [
  {
    id: "0001",
    descripcion: "INSTALACION DEL SERVICIO EDUCATIVO MODELO DEL NIVEL PRIMARIA Y SECUNDARIA EN EL ASENTAMIENTO HUMANO VISTA AL MAR MZ C DEL CENTRO POBLADO PAMPA INALAMBRICA DEL DISTRITO DE ILO, PROVINCIA DE ILO, REGION MOQUEGUA",
  },
  {
    id: "0002",
    descripcion: "MEJORAMIENTO Y AMPLIACION DEL SERVICIO DE EDUCACION INICIAL EN LA IEI 341 VISTA AL MAR, PAMPA INALAMBRICA DEL DISTRITO DE ILO - PROVINCIA DE ILO - DEPARTAMENTO DE MOQUEGUA",
  },
  {
    id: "0003",
    descripcion: "MEJORAMIENTO DEL SERVICIO DE EDUCACION SUPERIOR TECNOLOGICA DEL I.E.S.T.P. LUIS E. VALCARCEL, DISTRITO DE ILO - PROVINCIA DE ILO - DEPARTAMENTO DE MOQUEGUA",
  },
  {
    id: "0004",
    descripcion: "MEJORAMIENTO DEL SERVICIO EDUCATIVO DEL NIVEL PRIMARIA DE LA I.E. 43178 JOSE OLAYA BALANDRA EN EL DISTRITO DE ILO, PROVINCIA DE ILO Y DEPARTAMENTO DE MOQUEGUA",
  },
  {
    id: "0005",
    descripcion: "CREACION DEL SERVICIO EDUCATIVO DEL NIVEL INICIAL EN EL ASENTAMIENTO HUMANO PROMUVI XI DE LA PAMPA INALAMBRICA, DISTRITO DE ILO - PROVINCIA DE ILO - DEPARTAMENTO DE MOQUEGUA",
  },
  {
    id: "0006",
    descripcion: "MEJORAMIENTO Y AMPLIACION DEL SERVICIO EDUCATIVO EN LA I.E. 43026 CARLOS ALBERTO CONDE VASQUEZ DISTRITO DE ILO - PROVINCIA DE ILO - DEPARTAMENTO DE MOQUEGUA",
  },
  {
    id: "0007",
    descripcion: "MEJORAMIENTO Y AMPLIACION DE LOS SERVICIOS DE SALUD EN EL ESTABLECIMIENTO DE SALUD ESTRATEGICO CENTRO DE SALUD PAMPA INALAMBRICA DEL DISTRITO DE ILO - PROVINCIA DE ILO - DEPARTAMENTO DE MOQUEGUA",
  },
  {
    id: "0008",
    descripcion: "SIN DESCRIPCIÓN",
  },
  {
    id: "0009",
    descripcion: "GESTION ADMINISTRATIVA",
  },
  {
    id: "0010",
    descripcion: "SIN DESCRIPCIÓN",
  },
  {
    id: "0011",
    descripcion: "SIN DESCRIPCIÓN",
  },
  {
    id: "0012",
    descripcion: "SIN DESCRIPCIÓN",
  },
  {
    id: "0013",
    descripcion: "SIN DESCRIPCIÓN",
  },
  {
    id: "0014",
    descripcion: "CREACION SERVICIO DE ACOPIO Y COMERCIALIZACION DE PRODUCTOS HIDROBIOLOGICOS EN LA PAMPA INALAMBRICA DISTRITO DE ILO - PROVINCIA DE ILO - DEPARTAMENTO DE MOQUEGUA",
  },
  {
    id: "0015",
    descripcion: "MEJORAMIENTO DE LOS SERVICIOS DE ATENCION DE LA COMPAÑIA DE BOMBEROS BRIGADIER CBP JUAN PEÑALOZA SALAS Nº136, DEL DISTRITO DE ILO - PROVINCIA DE ILO - DEPARTAMENTO DE MOQUEGUA",
  },
  {
    id: "0016",
    descripcion: "ADQUISICION DE SISTEMA DE TECNOLOGIA, INFORMACION Y COMUNICACION; EN LA SUB REGION DE DESARROLLO ILO DISTRITO DE ILO, PROVINCIA ILO, DEPARTAMENTO MOQUEGUA",
  },
  {
    id: "0017",
    descripcion: "MEJORAMIENTO DEL SERVICIO DE EDUCACION SUPERIOR TECNOLOGICA DEL I.E.S.T.P. LUIS E. VALCARCEL, DISTRITO DE ILO - PROVINCIA DE ILO - DEPARTAMENTO DE MOQUEGUA",
  },
  {
    id: "0018",
    descripcion: "MEJORAMIENTO DEL SERVICIO DE EDUCACION SUPERIOR TECNOLOGICA DEL I.E.S.T.P. LUIS E. VALCARCEL, DISTRITO DE ILO - PROVINCIA DE ILO - DEPARTAMENTO DE MOQUEGUA",
  },
  {
    id: "0019",
    descripcion: "MEJORAMIENTO DEL SERVICIO DE EDUCACION SUPERIOR TECNOLOGICA DEL I.E.S.T.P. LUIS E. VALCARCEL, DISTRITO DE ILO - PROVINCIA DE ILO - DEPARTAMENTO DE MOQUEGUA",
  },
  {
    id: "0020",
    descripcion: "MEJORAMIENTO DEL SERVICIO DE EDUCACION SUPERIOR TECNOLOGICA DEL I.E.S.T.P. LUIS E. VALCARCEL, DISTRITO DE ILO - PROVINCIA DE ILO - DEPARTAMENTO DE MOQUEGUA",
  },
  {
    id: "0021",
    descripcion: "MEJORAMIENTO DEL SERVICIO DE EDUCACION SUPERIOR TECNOLOGICA DEL I.E.S.T.P. LUIS E. VALCARCEL, DISTRITO DE ILO - PROVINCIA DE ILO - DEPARTAMENTO DE MOQUEGUA",
  },
  {
    id: "0022",
    descripcion: "MEJORAMIENTO DEL SERVICIO DE EDUCACION SUPERIOR TECNOLOGICA DEL I.E.S.T.P. LUIS E. VALCARCEL, DISTRITO DE ILO - PROVINCIA DE ILO - DEPARTAMENTO DE MOQUEGUA",
  },
  {
    id: "0024",
    descripcion: "MEJORAMIENTO Y AMPLIACION DE LOS SERVICIOS DE SALUD EN EL ESTABLECIMIENTO DE SALUD ESTRATEGICO CENTRO DE SALUD PAMPA INALAMBRICA DEL DISTRITO DE ILO - PROVINCIA DE ILO - DEPARTAMENTO DE MOQUEGUA",
  },
  {
    id: "0025",
    descripcion: "MEJORAMIENTO Y AMPLIACION DE LOS SERVICIOS DE SALUD EN EL ESTABLECIMIENTO DE SALUD ESTRATEGICO CENTRO DE SALUD PAMPA INALAMBRICA DEL DISTRITO DE ILO - PROVINCIA DE ILO - DEPARTAMENTO DE MOQUEGUA",
  },
  {
    id: "0026",
    descripcion: "MEJORAMIENTO Y AMPLIACION DE LOS SERVICIOS DE SALUD EN EL ESTABLECIMIENTO DE SALUD ESTRATEGICO CENTRO DE SALUD PAMPA INALAMBRICA DEL DISTRITO DE ILO - PROVINCIA DE ILO - DEPARTAMENTO DE MOQUEGUA",
  },
  {
    id: "0027",
    descripcion: "MEJORAMIENTO Y AMPLIACION DE LOS SERVICIOS DE SALUD EN EL ESTABLECIMIENTO DE SALUD ESTRATEGICO CENTRO DE SALUD PAMPA INALAMBRICA DEL DISTRITO DE ILO - PROVINCIA DE ILO - DEPARTAMENTO DE MOQUEGUA",
  },
  {
    id: "0028",
    descripcion: "INSTALACION DEL SERVICIO EDUCATIVO MODELO DEL NIVEL PRIMARIA Y SECUNDARIA EN EL ASENTAMIENTO HUMANO VISTA AL MAR MZ C DEL CENTRO POBLADO PAMPA INALAMBRICA DEL DISTRITO DE ILO, PROVINCIA DE ILO, REGION MOQUEGUA",
  },
  {
    id: "0029",
    descripcion: "INSTALACION DEL SERVICIO EDUCATIVO MODELO DEL NIVEL PRIMARIA Y SECUNDARIA EN EL ASENTAMIENTO HUMANO VISTA AL MAR MZ C DEL CENTRO POBLADO PAMPA INALAMBRICA DEL DISTRITO DE ILO, PROVINCIA DE ILO, REGION MOQUEGUA",
  },
  {
    id: "0030",
    descripcion: "INSTALACION DEL SERVICIO EDUCATIVO MODELO DEL NIVEL PRIMARIA Y SECUNDARIA EN EL ASENTAMIENTO HUMANO VISTA AL MAR MZ C DEL CENTRO POBLADO PAMPA INALAMBRICA DEL DISTRITO DE ILO, PROVINCIA DE ILO, REGION MOQUEGUA",
  },
  {
    id: "0031",
    descripcion: "INSTALACION DEL SERVICIO EDUCATIVO MODELO DEL NIVEL PRIMARIA Y SECUNDARIA EN EL ASENTAMIENTO HUMANO VISTA AL MAR MZ C DEL CENTRO POBLADO PAMPA INALAMBRICA DEL DISTRITO DE ILO, PROVINCIA DE ILO, REGION MOQUEGUA",
  },
  {
    id: "0032",
    descripcion: "INSTALACION DEL SERVICIO EDUCATIVO MODELO DEL NIVEL PRIMARIA Y SECUNDARIA EN EL ASENTAMIENTO HUMANO VISTA AL MAR MZ C DEL CENTRO POBLADO PAMPA INALAMBRICA DEL DISTRITO DE ILO, PROVINCIA DE ILO, REGION MOQUEGUA",
  },
  {
    id: "0033",
    descripcion: "INSTALACION DEL SERVICIO EDUCATIVO MODELO DEL NIVEL PRIMARIA Y SECUNDARIA EN EL ASENTAMIENTO HUMANO VISTA AL MAR MZ C DEL CENTRO POBLADO PAMPA INALAMBRICA DEL DISTRITO DE ILO, PROVINCIA DE ILO, REGION MOQUEGUA",
  },
  {
    id: "0034",
    descripcion: "MEJORAMIENTO DEL SERVICIO DE EDUCACION INICIAL EN LA IEI 231 BELLO HORIZONTE, DISTRITO DE ILO - PROVINCIA DE ILO - DEPARTAMENTO DE MOQUEGUA",
  },
  {
    id: "0035",
    descripcion: "MEJORAMIENTO DEL SERVICIO DE EDUCACION INICIAL EN LA IEI 231 BELLO HORIZONTE, DISTRITO DE ILO - PROVINCIA DE ILO - DEPARTAMENTO DE MOQUEGUA",
  },
  {
    id: "0036",
    descripcion: "MEJORAMIENTO DEL SERVICIO DE EDUCACION INICIAL EN LA IEI 231 BELLO HORIZONTE, DISTRITO DE ILO - PROVINCIA DE ILO - DEPARTAMENTO DE MOQUEGUA",
  },
  {
    id: "0037",
    descripcion: "MEJORAMIENTO DEL SERVICIO DE EDUCACION INICIAL EN LA IEI 231 BELLO HORIZONTE, DISTRITO DE ILO - PROVINCIA DE ILO - DEPARTAMENTO DE MOQUEGUA",
  },
  {
    id: "0038",
    descripcion: "MEJORAMIENTO DEL SERVICIO DE EDUCACION INICIAL EN LA IEI 231 BELLO HORIZONTE, DISTRITO DE ILO - PROVINCIA DE ILO - DEPARTAMENTO DE MOQUEGUA",
  },
  {
    id: "0039",
    descripcion: "MEJORAMIENTO DEL SERVICIO DE EDUCACION INICIAL EN LA IEI 231 BELLO HORIZONTE, DISTRITO DE ILO - PROVINCIA DE ILO - DEPARTAMENTO DE MOQUEGUA",
  },
  {
    id: "0040",
    descripcion: "MEJORAMIENTO DEL SERVICIO DE EDUCACION INICIAL EN LA IEI 231 BELLO HORIZONTE, DISTRITO DE ILO - PROVINCIA DE ILO - DEPARTAMENTO DE MOQUEGUA",
  },
  {
    id: "0042",
    descripcion: "MEJORAMIENTO DEL SERVICIO EDUCATIVO DEL NIVEL PRIMARIA DE LA I.E. 43178 JOSE OLAYA BALANDRA",
  },
  {
    id: "0043",
    descripcion: "MEJORAMIENTO DEL SERVICIO EDUCATIVO DEL NIVEL PRIMARIA DE LA I.E. 43178 JOSE OLAYA BALANDRA TCGEN",
  },
  {
    id: "0044",
    descripcion: "MEJORAMIENTO DEL SERVICIO EDUCATIVO DEL NIVEL PRIMARIA DE LA I.E. 43178 JOSE OLAYA BALANDRA",
  },
  {
    id: "0045",
    descripcion: "MEJORAMIENTO DEL SERVICIO EDUCATIVO DEL NIVEL PRIMARIA DE LA I.E. 43178 JOSE OLAYA BALANDRA",
  },
  {
    id: "0046",
    descripcion: "MEJORAMIENTO DEL SERVICIO EDUCATIVO DEL NIVEL PRIMARIA DE LA I.E. 43178 JOSE OLAYA BALANDRA",
  },
  {
    id: "0047",
    descripcion: "MEJORAMIENTO DEL SERVICIO EDUCATIVO DEL NIVEL PRIMARIA DE LA I.E. 43178 JOSE OLAYA BALANDRA",
  },
  {
    id: "0048",
    descripcion: "MEJORAMIENTO DEL SERVICIO EDUCATIVO DEL NIVEL PRIMARIA DE LA I.E. 43178 JOSE OLAYA BALANDRA",
  },
  {
    id: "0049",
    descripcion: "CREACION DEL SERVICIO EDUCATIVO DEL NIVEL INICIAL EN EL ASENTAMIENTO HUMANO PROMUVI XI DE LA PAMPA INALAMBRICA",
  },
  {
    id: "0050",
    descripcion: "CREACION DEL SERVICIO EDUCATIVO DEL NIVEL INICIAL EN EL ASENTAMIENTO HUMANO PROMUVI XI DE LA PAMPA INALAMBRICA",
  },
  {
    id: "0051",
    descripcion: "CREACION DEL SERVICIO EDUCATIVO DEL NIVEL INICIAL EN EL ASENTAMIENTO HUMANO PROMUVI XI DE LA PAMPA INALAMBRICA",
  },
  {
    id: "0052",
    descripcion: "CREACION DEL SERVICIO EDUCATIVO DEL NIVEL INICIAL EN EL ASENTAMIENTO HUMANO PROMUVI XI DE LA PAMPA INALAMBRICA",
  },
  {
    id: "0053",
    descripcion: "CREACION DEL SERVICIO EDUCATIVO DEL NIVEL INICIAL EN EL ASENTAMIENTO HUMANO PROMUVI XI DE LA PAMPA INALAMBRICA",
  },
  {
    id: "0054",
    descripcion: "CREACION DEL SERVICIO EDUCATIVO DEL NIVEL INICIAL EN EL ASENTAMIENTO HUMANO PROMUVI XI DE LA PAMPA INALAMBRICA",
  },
  {
    id: "0055",
    descripcion: "CREACION DEL SERVICIO EDUCATIVO DEL NIVEL INICIAL EN EL ASENTAMIENTO HUMANO PROMUVI XI DE LA PAMPA INALAMBRICA",
  },
  {
    id: "0056",
    descripcion: "MANTENIMIENTO DE INFRAESTRUCTURA",
  },
  {
    id: "0057",
    descripcion: "MANTENIMIENTO DE LA INFRAESTRUCTURA DEL PABELLON Nº 03 E IMPERMEABILIZACION SUPERIOR DEL PABELLON Nº 02 DE LA I.E. 43031 JHON F. KENNEDY, DISTRITO DE ILO - ILO - MOQUEGUA",
  },
  {
    id: "0058",
    descripcion: "MANTENIMIENTO DE LA INFRAESTRUCTURA DEL PABELLON E DE LA I.E. AMERICO GARIBALDI GHERSI, DISTRITO DE PACOCHA - ILO - MOQUEGUA",
  },
  {
    id: "0059",
    descripcion: "MANTENIMIENTO DE LA INFRAESTRUCTURA DE LA I.E. N° 303 MIGUEL GRAU Y DEL CERCO PERIMETRICO DE LA I.E. JORGE BASADRE GROHMANN, DISTRITO ILO - ILO - MOQUEGUA",
  },
  {
    id: "0060",
    descripcion: "MANTENIMIENTO DE LA INFRAESTRUCTURA DEL NIVEL INICIAL Y CERCO PERIMETRICO DEL NIVEL PRIMARIO DE LA I.E. N° 43026 CARLOS ALBERTO CONDE VASQUEZ, DISTRITO ILO - ILO - MOQUEGUA",
  },
  {
    id: "0061",
    descripcion: "MANTENIMIENTO DE LA INFRAESTRUCTURA DE LA I.E. MARISCAL ANDRES AVELINO CACERES, DISTRITO ILO - ILO - MOQUEGUA",
  },
  {
    id: "0062",
    descripcion: "MANTENIMIENTO DE LA INFRAESTRUCTURA DE LA I.E. MERCEDES CABELLO DE CARBONERA, DISTRITO ILO - ILO - MOQUEGUA",
  },
  {
    id: "0063",
    descripcion: "MANTENIMIENTO DE LA INFRAESTRUCTURA DEL CENTRO DE SALUD ALTO ILO, DISTRITO DE ILO, ILO, MOQUEGUA",
  },
  {
    id: "0064",
    descripcion: "MANTENIMIENTO DE LA INFRAESTRUCTURA DEL PUESTO DE SALUD JHON F. KENNEDY, DISTRITO ILO - ILO - MOQUEGUA",
  },
  {
    id: "0065",
    descripcion: "MANTENIMIENTO EXTERIOR DE LOS PABELLONES A, B, C, D, E, F, G Y LOSA DEPORTIVA DE LA I.E. CNEL. FRANCISCO BOLOGNESI CERVANTES, DISTRITO ILO - ILO - MOQUEGUA",
  },
  {
    id: "0066",
    descripcion: "MEJORAMIENTO DE LOS SERVICIOS DE ATENCION DE LA COMPAÑIA DE BOMBEROS BRIGADIER CBP JUAN PEÑALOZA SALAS Nº136",
  },
  {
    id: "0067",
    descripcion: "MEJORAMIENTO DE LOS SERVICIOS DE ATENCION DE LA COMPAÑIA DE BOMBEROS BRIGADIER CBP JUAN PEÑALOZA SALAS Nº136",
  },
  {
    id: "0070",
    descripcion: "MEJORAMIENTO DE LOS SERVICIOS DE ATENCION DE LA COMPAÑIA DE BOMBEROS BRIGADIER CBP JUAN PEÑALOZA SALAS Nº136",
  },
  {
    id: "0071",
    descripcion: "MEJORAMIENTO DE LOS SERVICIOS DE ATENCION DE LA COMPAÑIA DE BOMBEROS BRIGADIER CBP JUAN PEÑALOZA SALAS Nº136",
  },
  {
    id: "0072",
    descripcion: "MEJORAMIENTO DE LOS SERVICIOS DE ATENCION DE LA COMPAÑIA DE BOMBEROS BRIGADIER CBP JUAN PEÑALOZA SALAS Nº136",
  },
  {
    id: "0073",
    descripcion: "MEJORAMIENTO DE LOS SERVICIOS DE ATENCION DE LA COMPAÑIA DE BOMBEROS BRIGADIER CBP JUAN PEÑALOZA SALAS Nº136",
  },
  {
    id: "0074",
    descripcion: "MANTENIMIENTO DE INFRAESTRUCTURA EDUCATIVA",
  },
  {
    id: "0075",
    descripcion: "ESTUDIOS DE PRE-INVERSION",
  },
  {
    id: "0076",
    descripcion: "CREACION SERVICIO DE ACOPIO Y COMERCIALIZACION DE PRODUCTOS HIDROBIOLOGICOS EN LA PAMPA INALAMBRICA",
  },
  {
    id: "0077",
    descripcion: "CREACION SERVICIO DE ACOPIO Y COMERCIALIZACION DE PRODUCTOS HIDROBIOLOGICOS EN LA PAMPA INALAMBRICA",
  },
  {
    id: "0078",
    descripcion: "CREACION SERVICIO DE ACOPIO Y COMERCIALIZACION DE PRODUCTOS HIDROBIOLOGICOS EN LA PAMPA INALAMBRICA",
  },
  {
    id: "0079",
    descripcion: "CREACION SERVICIO DE ACOPIO Y COMERCIALIZACION DE PRODUCTOS HIDROBIOLOGICOS EN LA PAMPA INALAMBRICA",
  },
  {
    id: "0080",
    descripcion: "CREACION SERVICIO DE ACOPIO Y COMERCIALIZACION DE PRODUCTOS HIDROBIOLOGICOS EN LA PAMPA INALAMBRICA",
  },
  {
    id: "0081",
    descripcion: "CREACION SERVICIO DE ACOPIO Y COMERCIALIZACION DE PRODUCTOS HIDROBIOLOGICOS EN LA PAMPA INALAMBRICA",
  },
  {
    id: "0082",
    descripcion: "MEJORAMIENTO DEL SERVICIO EDUCATIVO EN LA INSTITUCION EDUCATIVA EMBLEMATICA ALMIRANTE MIGUEL GRAU SEMINARIO, SECTOR PAMPA INALAMBRICA",
  },
  {
    id: "0083",
    descripcion: "MEJORAMIENTO DEL SERVICIO EDUCATIVO EN LA INSTITUCION EDUCATIVA EMBLEMATICA ALMIRANTE MIGUEL GRAU SEMINARIO, SECTOR PAMPA INALAMBRICA",
  },
  {
    id: "0084",
    descripcion: "MEJORAMIENTO DEL SERVICIO EDUCATIVO EN LA INSTITUCION EDUCATIVA EMBLEMATICA ALMIRANTE MIGUEL GRAU SEMINARIO, SECTOR PAMPA INALAMBRICA",
  },
  {
    id: "0085",
    descripcion: "MEJORAMIENTO DEL SERVICIO EDUCATIVO EN LA INSTITUCION EDUCATIVA EMBLEMATICA ALMIRANTE MIGUEL GRAU SEMINARIO, SECTOR PAMPA INALAMBRICA",
  },
  {
    id: "0086",
    descripcion: "MEJORAMIENTO DEL SERVICIO EDUCATIVO EN LA INSTITUCION EDUCATIVA EMB  EMBLEMATICA ALMIRANTE MIGUEL GRAU SEMINARIO, SECTOR PAMPA INALAMBRICA",
  },
  {
    id: "0087",
    descripcion: "ADQUISICION DE EQUIPOS BIOMEDICOS; EN EL HOSPITAL ILO",
  },
  {
    id: "0088",
    descripcion: "ADQUISICION DE EQUIPOS BIOMEDICOS; EN EL HOSPITAL ILO",
  },
  {
    id: "0089",
    descripcion: "SIN DESCRIPCIÓN",
  },
  {
    id: "0090",
    descripcion: "MEJORAMIENTO DEL SERVICIO DE EDUCACION SUPERIOR TECNOLOGICA DEL I.E.S.T.P. LUIS E. VALCARCEL, DISTRITO DE ILO - PROVINCIA DE ILO - DEPARTAMENTO DE MOQUEGUA",
  },
  {
    id: "0091",
    descripcion: "INSTALACION DEL SERVICIO DE APOYO A LA CADENA PRODUCTIVA DEL RECURSO CHORO EN EL LITORAL MARINO DE LA PROVINCIA DE ILO - REGION MOQUEGUA",
  },
  {
    id: "0092",
    descripcion: "INSTALACION DEL SERVICIO DE APOYO A LA CADENA PRODUCTIVA DEL RECURSO CHORO EN EL LITORAL MARINO DE LA PROVINCIA DE ILO - REGION MOQUEGUA",
  },
  {
    id: "0093",
    descripcion: "INSTALACION DEL SERVICIO DE APOYO A LA CADENA PRODUCTIVA DEL RECURSO CHORO EN EL LITORAL MARINO DE LA PROVINCIA DE ILO - REGION MOQUEGUA",
  },
  {
    id: "0094",
    descripcion: "INSTALACION DEL SERVICIO DE APOYO A LA CADENA PRODUCTIVA DEL RECURSO CHORO EN EL LITORAL MARINO DE LA PROVINCIA DE ILO - REGION MOQUEGUA",
  },
  {
    id: "0095",
    descripcion: "INSTALACION DEL SERVICIO DE APOYO A LA CADENA PRODUCTIVA DEL RECURSO CHORO EN EL LITORAL MARINO DE LA PROVINCIA DE ILO - REGION MOQUEGUA",
  },
  {
    id: "0096",
    descripcion: "SIN DESCRIPCIÓN",
  },
  {
    id: "0097",
    descripcion: "SIN DESCRIPCIÓN",
  },
  {
    id: "0098",
    descripcion: "SIN DESCRIPCIÓN",
  },
  {
    id: "0099",
    descripcion: "SIN DESCRIPCIÓN",
  },
  {
    id: "0100",
    descripcion: "SIN DESCRIPCIÓN",
  },
  {
    id: "0101",
    descripcion: "SIN DESCRIPCIÓN",
  },
  {
    id: "0102",
    descripcion: "MEJORAMIENTO DEL SERVICIO EDUCATIVO EN LA I.E. 43027 MARISCAL DOMINGO NIETO MARQUEZ ILO DEL DISTRITO DE ILO - PROVINCIA DE ILO - DEPARTAMENTO DE MOQUEGUA",
  },
  {
    id: "0103",
    descripcion: "SIN DESCRIPCIÓN",
  },
  {
    id: "0104",
    descripcion: "SIN DESCRIPCIÓN",
  },
  {
    id: "0105",
    descripcion: "SIN DESCRIPCIÓN",
  },
  {
    id: "0106",
    descripcion: "SIN DESCRIPCIÓN",
  },
  {
    id: "0107",
    descripcion: "SIN DESCRIPCIÓN",
  },
  {
    id: "0109",
    descripcion: "MANTENIMIENTO DE LA INFRAESTRUCTURA DE LA I.E. Nº 43030 NYLON PEDRO Y LA INFRAESTRUCTURA DE LA I.E. 247 LUZMILA CASTRO DE CHAVEZ DISTRITO ILO, ILO, MOQUEGUA",
  },
  {
    id: "0110",
    descripcion: "MANTENIMIENTO DE LA INFRAESTRUCTURA DE LA EMBLEMATICA INSTITUCION EDUCATIVA ALMIRANTE MIGUEL GRAU SEMINARIO, DISTRITO ILO, ILO, MOQUEGUA",
  },
  {
    id: "0111",
    descripcion: "MANTENIMIENTO DE LA INFRAESTRUCTURA DE LA I.E.I. N° 337 PAUL HARRIS Y LA INFRAESTRUCTURA DE LA I.E.I. N° 361 NUEVA VICTORIA DEL DISTRITO Y PROVINCIA DE ILO REGION MOQUEGUA",
  },
  {
    id: "0112",
    descripcion: "MANTENIMIENTO DE LA INFRAESTRUCTURA PUESTO DE SALUD LOS ANGELES, DISTRITO Y PROVINCIA DE ILO, REGION MOQUEGUA",
  },
  {
    id: "0117",
    descripcion: "MANTENIMIENTO DE LA INFRAESTRUCTURA DE LA IEPM COLEGIO MILITAR MARISCAL DOMINGO NIETO, DISTRITO PACOCHA, ILO, MOQUEGUA",
  },
  {
    id: "0119",
    descripcion: "SIN DESCRIPCIÓN",
  },
  {
    id: "0120",
    descripcion: "SIN DESCRIPCIÓN",
  },
  {
    id: "0122",
    descripcion: "MANTENIMIENTO DE LA INFRAESTRUCTURA DE LA I.E. DANIEL BECERRA OCAMPO, DISTRITO Y PROVINCIA DE ILO, REGION MOQUEGUA",
  },
];