import { StyleSheet } from "@react-pdf/renderer";

export const styles = StyleSheet.create({
  page: { 
    flexDirection: "column",
    padding: 20,
    backgroundColor: "transparent",
  },
  image: {
    width: 60,
    height: 40,
    marginBottom: 5,
    position: "relative",
    zIndex: 1,
  },
  boldText: {
    fontWeight: "bold",
    marginLeft: 10,
    fontSize: 6,
  },
  titleText: {
    fontWeight: "bold",
    fontSize: 12,
    textAlign: "center",
  },
  table: { 
    width: "100%", 
    marginTop: 5,
    borderTop: 1,
    borderTopColor: "#000",
    borderRight: 1,
    borderRightColor: "#000",
  },
  row: {
    flexDirection: "row",
    borderBottom: 1,
    borderBottomColor: "#000",
    minHeight: 15,
    alignItems: "center",
  },
  cell: {
    fontSize: 6,
    padding: 3,
    borderLeft: 1,
    borderLeftColor: "#000",
  },
  headerCell: {
    fontSize: 6,
    padding: 3,
    backgroundColor: "#dcdcdc",
    fontWeight: "bold",
    borderLeft: 1,
    borderLeftColor: "#000",
  },
  itemCell: {
    width: 40,
    textAlign: "left",
    fontSize: 6,
    padding: 3,
    borderLeft: 1,
    borderLeftColor: "#000",
  },
  itemHeaderCell: {
    width: 40,
    textAlign: "left",
    fontSize: 6,
    padding: 3,
    backgroundColor: "#dcdcdc",
    fontWeight: "bold",
    borderLeft: 1,
    borderLeftColor: "#000",
  },
  codigoCell: {
    width: 80,
    textAlign: "center",
    fontSize: 6,
    padding: 3,
    borderLeft: 1,
    borderLeftColor: "#000",
  },
  codigoHeaderCell: {
    width: 80,
    textAlign: "center",
    fontSize: 6,
    padding: 3,
    backgroundColor: "#dcdcdc",
    fontWeight: "bold",
    borderLeft: 1,
    borderLeftColor: "#000",
  },
  cantidadCell: {
    width: 60,
    textAlign: "center",
    fontSize: 6,
    padding: 3,
    borderLeft: 1,
    borderLeftColor: "#000",
  },
  cantidadHeaderCell: {
    width: 60,
    textAlign: "center",
    fontSize: 6,
    padding: 3,
    backgroundColor: "#dcdcdc",
    fontWeight: "bold",
    borderLeft: 1,
    borderLeftColor: "#000",
  },
  descripcionCell: {
    width: 260,
    textAlign: "center",
    fontSize: 6,
    padding: 3,
    borderLeft: 1,
    borderLeftColor: "#000",
  },
  descripcionHeaderCell: {
    width: 260,
    textAlign: "center",
    fontSize: 6,
    padding: 3,
    backgroundColor: "#dcdcdc",
    fontWeight: "bold",
    borderLeft: 1,
    borderLeftColor: "#000",
  },
  cuentaCell: {
    width: 90,
    textAlign: "center",
    fontSize: 6,
    padding: 3,
    borderLeft: 1,
    borderLeftColor: "#000",
  },
  cuentaHeaderCell: {
    width: 90,
    textAlign: "center",
    fontSize: 6,
    padding: 3,
    backgroundColor: "#dcdcdc",
    fontWeight: "bold",
    borderLeft: 1,
    borderLeftColor: "#000",
  },
  cantDespCell: {
    width: 90,
    textAlign: "center",
    fontSize: 6,
    padding: 3,
    borderLeft: 1,
    borderLeftColor: "#000",
  },
  cantDespHeaderCell: {
    width: 90,
    textAlign: "center",
    fontSize: 6,
    padding: 3,
    backgroundColor: "#dcdcdc",
    fontWeight: "bold",
    borderLeft: 1,
    borderLeftColor: "#000",
  },
  precioUnitCell: {
    width: 90,
    textAlign: "center",
    fontSize: 6,
    padding: 3,
    borderLeft: 1,
    borderLeftColor: "#000",
  },
  precioUnitHeaderCell: {
    width: 90,
    textAlign: "center",
    fontSize: 6,
    padding: 3,
    backgroundColor: "#dcdcdc",
    fontWeight: "bold",
    borderLeft: 1,
    borderLeftColor: "#000",
  },
  totalCell: {
    width: 90,
    textAlign: "center",
    fontSize: 6,
    padding: 3,
    borderLeft: 1,
    borderLeftColor: "#000",
  },
  totalHeaderCell: {
    width: 90,
    textAlign: "center",
    fontSize: 6,
    padding: 3,
    backgroundColor: "#dcdcdc",
    fontWeight: "bold",
    borderLeft: 1,
    borderLeftColor: "#000",
  },
  totalRow: {
    flexDirection: "row",
    borderBottom: 1,
    borderBottomColor: "#000",
    minHeight: 15,
    alignItems: "center",
    backgroundColor: "#dcdcdc",
  },
  totalPrecioUnitCell: {
    width: 90,
    textAlign: "center",
    fontSize: 6,
    padding: 3,
    borderLeft: 1,
    borderLeftColor: "#000",
    fontWeight: "bold",
    backgroundColor: "#dcdcdc",
  },
  totalTotalCell: {
    width: 84,
    textAlign: "center",
    fontSize: 6,
    padding: 3,
    borderLeft: 1,
    borderLeftColor: "#000",
    fontWeight: "bold",
    backgroundColor: "#dcdcdc",
  },
  emptyCell: {
    width: 40,
    fontSize: 6,
    padding: 3,
    borderLeft: 1,
    borderLeftColor: "#000",
    backgroundColor: "#dcdcdc",
  },
  emptyCellWide: {
    width: 80,
    fontSize: 6,
    padding: 3,
    borderLeft: 0,
    borderLeftColor: "#000",
    backgroundColor: "#dcdcdc",
  },
  emptyCellMedium: {
    width: 60,
    fontSize: 6,
    padding: 3,
    borderLeft: 0,
    borderLeftColor: "#000",
    backgroundColor: "#dcdcdc",
  },
  emptyCellExtraWide: {
    width: 260,
    fontSize: 6,
    padding: 3,
    borderLeft: 0,
    borderLeftColor: "#000",
    backgroundColor: "#dcdcdc",
  },
  emptyCellLong: {
    width: 90,
    fontSize: 6,
    padding: 3,
    borderLeft: 0,
    borderLeftColor: "#000",
    backgroundColor: "#dcdcdc",
  },
  body: {
    flex: 1,
    flexDirection: "column",
  },
  footer: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderTop: 1,
    borderTopColor: "#000",
    paddingTop: 10,
    marginTop: 20,
  },
  signature: {
    flex: 1,
    alignItems: "center",
    marginHorizontal: 5,
  },
  signatureLine: {
    width: 100,
    marginBottom: 3,
  },
  signatureText: {
    fontSize: 6,
    textAlign: "center",
  },
  unidadmedidaCell: {
    width: 90,
    textAlign: "center",
    fontSize: 6,
    padding: 3,
    borderLeft: 1,
    borderLeftColor: "#000",
  },
  unidadmedidaHeaderCell: {
    width: 90,
    textAlign: "center",
    fontSize: 6,
    padding: 3,
    backgroundColor: "#dcdcdc",
    fontWeight: "bold",
    borderLeft: 1,
    borderLeftColor: "#000",
  },
});